version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: umbraco-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"